targets:
  $default:
    builders:
      adaptive_api|adaptiveBuilder:
        options:
          adaptive_variants: mobileApp, mobileWeb, desktopApp, desktopWeb
          adaptive_variants_optional: false
          output_location: lib/generated/