name: example
description: An example app consuming adaptive_api

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dev_dependencies:
  adaptive_api:
    path: '../../adaptive_api'
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0