builders:
  adaptiveBuilder:
    import: 'package:adaptive_api/adaptive_api.dart'
    builder_factories: ['adaptiveBuilder']
    build_extensions: { r'$lib$' : [ 'adaptive_api.g.dart' ] }
    build_to: source
    auto_apply: dependents